;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cprintf
	.import		_cgetc
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$25,$30,$32,$58,$0A,$0D,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; unsigned char c = cgetc();
;
L0002:	jsr     _cgetc
	jsr     pusha
;
; cprintf("%02x\r\n", c);
;
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	jsr     _cprintf
;
; }
;
	jsr     incsp1
;
; while(1)
;
	jmp     L0002

.endproc

